version: '3.4'

services:
  20200815foodhygieneratingsmap:
    image: 20200815foodhygieneratingsmap
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
